### ISSUE TITLE
Any plans to open source?

### ISSUE THREAD

**Issue by xorange** [KeliCheng/Simpo#1]
工具很有趣。menu bar application的想法很棒，只能看到自己的post的想法很好，样式也很好看。

请问有开源的打算吗？

**Comment by kelicheng** [comment]
你好，现在支持的各个平台都改了api规则，所以app基本用不了了，而且当时用的swift版本太老，现在xcode也不支持了，所以就不开源啦。

**Comment by xorange** [comment]
好的，谢谢。昨天刚安装的，还能使用～
